viaa:
  logging:
    level: DEBUG
app:
  environment: !ENV ${ENVIRONMENT}
  teamleader:
    auth_uri: !ENV ${TL_AUTH_URI}
    api_uri: !ENV ${TL_API_URI}
    client_id: !ENV ${TL_CLIENT_ID}
    client_secret: !ENV ${TL_CLIENT_SECRET}
    redirect_uri: !ENV ${TL_REDIRECT_URI}
    secret_code_state: !ENV ${TL_SECRET_CODE_STATE}
    code: !ENV ${TL_CODE}
    auth_token: !ENV ${TL_AUTH_TOKEN}
    refresh_token: !ENV ${TL_REFRESH_TOKEN}
    redis_url: !ENV ${REDIS_URL}
  ldap:
    bind: !ENV ${LDAP_BIND}
    URI: !ENV ${LDAP_URI}
    password: !ENV ${LDAP_PASSWORD}
  slack:
    channel: !ENV ${SLACK_CHANNEL}
    token: !ENV ${SLACK_TOKEN}
  skryv:
    webhook_url: !ENV ${WEBHOOK_URL}
    webhook_jwt: !ENV ${WEBHOOK_JWT} 
    dossier_content_partner_id: !ENV ${SKRYV_DOSSIER_CP_ID}
  custom_field_ids:
    opstartfase: !ENV ${TL_OPSTARTFASE}
    cp_status: !ENV ${TL_CPSTATUS}
    intentieverklaring: !ENV ${TL_INTENTIEVERKLARING}
    toestemming_starten: !ENV ${TL_TOESTEMMING_STARTEN}
    swo: !ENV ${TL_SWO}
    swo_addenda: !ENV ${TL_SWO_ADDENDA}
    type_organisatie: !ENV ${TL_TYPE_ORGANISATIE}
    facturatie_email: !ENV ${TL_FACTURATIE_EMAIL}
    bestelbon: !ENV ${TL_BESTELBON}
    relatie_meemoo: !ENV ${TL_RELATIE_MEEMOO}
    functie_category: !ENV ${TL_FUNCTIE_CATEGORY}
  business_types:
    ag: !ENV ${TL_BT_AG}
    bvba: !ENV ${TL_BT_BVBA}
    cvba: !ENV ${TL_BT_CVBA}
    cvoa: !ENV ${TL_BT_CVOA}
    comm.v: !ENV ${TL_BT_COMMV}
    comm.va: !ENV ${TL_BT_COMMVA}
    esv: !ENV ${TL_BT_ESV}
    ebvba: !ENV ${TL_BT_EBVBA}
    eenmanszaak: !ENV ${TL_BT_EENMANSZAAK}
    lv: !ENV ${TL_BT_LV}
    nv: !ENV ${TL_BT_NV}
    sbvba: !ENV ${TL_BT_SBVBA}
    se: !ENV ${TL_BT_SE}
    vof: !ENV ${TL_BT_VOF}
    vzw: !ENV ${TL_BT_VZW}
    vereniging: !ENV ${TL_BT_VERENIGING}
