viaa:
  logging:
    level: DEBUG
app:
  environment: !ENV ${ENVIRONMENT}
  teamleader:
    auth_uri: !ENV ${TL_AUTH_URI}
    api_uri: !ENV ${TL_API_URI}
    client_id: !ENV ${TL_CLIENT_ID}
    client_secret: !ENV ${TL_CLIENT_SECRET}
    redirect_uri: !ENV ${TL_REDIRECT_URI}
    secret_code_state: !ENV ${TL_SECRET_CODE_STATE}
    code: !ENV ${TL_CODE}
    auth_token: !ENV ${TL_AUTH_TOKEN}
    refresh_token: !ENV ${TL_REFRESH_TOKEN}
    token_file: !ENV ${TL_TOKEN_FILE}
    redis_url: !ENV ${REDIS_URL}
  ldap:
    bind: !ENV ${LDAP_BIND}
    URI: !ENV ${LDAP_URI}
    password: !ENV ${LDAP_PASSWORD}
  slack:
    channel: !ENV ${SLACK_CHANNEL}
    token: !ENV ${SLACK_TOKEN}
  skryv:
    webhook_url: !ENV ${WEBHOOK_URL}
    webhook_jwt: !ENV ${WEBHOOK_JWT} 
  custom_field_labels:
    company_kring: '2.2 - CP status'
    company_kring: '2.3 - Intentieverklaring'
    company_kring: '2.4 - Toestemming starten'
    company_kring: '2.5 - SWO'
    company_kring: '2.6 - SWO addenda'

